# Generated by Django 6.0 on 2025-12-18 16:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_googleaccount"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="wishitem",
            name="owner",
            field=models.ForeignKey(
                default=int,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="wish_items",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
