# Generated by Django 6.0 on 2026-01-28 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_yandexaccount"),
    ]

    operations = [
        migrations.AddField(
            model_name="wishitem",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="wish_items/"),
        ),
    ]
