# Generated by Django 6.0.2 on 2026-02-23 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_remove_wishitem_image_wishitem_image_key_event"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="link",
            field=models.URLField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="wishitem",
            name="currency",
            field=models.CharField(
                blank=True,
                choices=[
                    ("rub", "RUB"),
                    ("usd", "USD"),
                    ("eur", "EUR"),
                    ("byn", "BYN"),
                    ("kzt", "KZT"),
                    ("jpy", "JPY"),
                    ("krw", "KRW"),
                    ("try", "TRY"),
                    ("aed", "AED"),
                    ("ils", "ILS"),
                    ("uzs", "UZS"),
                    ("kgs", "KGS"),
                    ("gbp", "GBP"),
                    ("chf", "CHF"),
                    ("uah", "UAH"),
                    ("pln", "PLN"),
                ],
                default="",
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="wishitem",
            name="link",
            field=models.URLField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="wishitem",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
    ]
