# Generated by Django 6.0.2 on 2026-02-23 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_event_link_wishitem_currency_wishitem_link_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="notify_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="event",
            name="repeat_yearly",
            field=models.BooleanField(default=False),
        ),
    ]
