# Generated by Django 6.0.2 on 2026-04-06 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_event_notify_enabled_event_repeat_yearly"),
    ]

    operations = [
        migrations.CreateModel(
            name="Collection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=128, unique=True)),
                ("title", models.CharField(max_length=255)),
                ("subtitle", models.CharField(blank=True, max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "section",
                    models.CharField(
                        choices=[
                            ("for_you", "Подборки для вас"),
                            ("by_character", "Подборки по характеру"),
                            ("editorial", "Редакторские подборки"),
                        ],
                        max_length=32,
                    ),
                ),
                ("badge", models.CharField(blank=True, max_length=64)),
                ("cover_image_url", models.URLField(blank=True, default="")),
                ("tags", models.JSONField(blank=True, default=list)),
                ("items_total", models.PositiveIntegerField(default=0)),
                ("sort_order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["section", "sort_order", "id"],
                "indexes": [
                    models.Index(
                        fields=["section", "sort_order"],
                        name="api_collect_section_b70b32_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="CollectionItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("link", models.URLField(blank=True, default="")),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("rub", "RUB"),
                            ("usd", "USD"),
                            ("eur", "EUR"),
                            ("byn", "BYN"),
                            ("kzt", "KZT"),
                            ("jpy", "JPY"),
                            ("krw", "KRW"),
                            ("try", "TRY"),
                            ("aed", "AED"),
                            ("ils", "ILS"),
                            ("uzs", "UZS"),
                            ("kgs", "KGS"),
                            ("gbp", "GBP"),
                            ("chf", "CHF"),
                            ("uah", "UAH"),
                            ("pln", "PLN"),
                        ],
                        default="",
                        max_length=8,
                    ),
                ),
                ("image_url", models.URLField(blank=True, default="")),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="api.collection",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.AddField(
            model_name="wishitem",
            name="collection_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="wish_items",
                to="api.collectionitem",
            ),
        ),
        migrations.AddIndex(
            model_name="collectionitem",
            index=models.Index(
                fields=["collection", "sort_order"],
                name="api_collect_collect_095279_idx",
            ),
        ),
    ]
