# Generated by Django 6.0.2 on 2026-04-06 13:34

from decimal import Decimal

from django.db import migrations

COLLECTIONS = [
    {
        "slug": "book-lovers",
        "title": "Книголюбы",
        "subtitle": "Идеи для тех, кто готов потеряться в новой истории",
        "description": (
            "Выберите книгу и приятные аксессуары для любимого человека - "
            "подарите ему возможность отвлечься от рутины и погрузиться в новые миры."
        ),
        "section": "for_you",
        "cover_image_url": "https://placehold.co/600x600/png?text=Book+Lovers",
        "tags": ["Саморазвитие", "Для детей", "Фантастика"],
        "items_total": 15,
        "sort_order": 10,
        "items": [
            {
                "title": "Kindle Paperwhite",
                "description": "Легкая электронная книга с теплой подсветкой для чтения вечерами.",
                "link": "https://example.com/book-lovers/kindle-paperwhite",
                "price": Decimal("18990.00"),
                "currency": "rub",
                "image_url": "https://placehold.co/600x800/png?text=Kindle",
                "sort_order": 10,
            },
            {
                "title": "Коллекционное издание 'Дюна'",
                "description": "Подарочное издание для тех, кто любит фантастику и красивые полки.",
                "link": "https://example.com/book-lovers/dune",
                "price": Decimal("4590.00"),
                "currency": "rub",
                "image_url": "https://placehold.co/600x800/png?text=Dune",
                "sort_order": 20,
            },
            {
                "title": "Набор дизайнерских закладок",
                "description": "Минималистичный набор металлических закладок на каждый день.",
                "link": "https://example.com/book-lovers/bookmarks",
                "price": Decimal("1290.00"),
                "currency": "rub",
                "image_url": "https://placehold.co/600x800/png?text=Bookmarks",
                "sort_order": 30,
            },
            {
                "title": "Подписка на аудиокниги",
                "description": "Годовой доступ к подборкам аудиокниг и подкастов.",
                "link": "https://example.com/book-lovers/audiobooks",
                "price": Decimal("3990.00"),
                "currency": "rub",
                "image_url": "https://placehold.co/600x800/png?text=Audiobooks",
                "sort_order": 40,
            },
        ],
    },
    {
        "slug": "top-24-hours",
        "title": "ТОП 24 часа",
        "subtitle": "Самые популярные идеи прямо сейчас",
        "description": (
            "Подборка подарков, которые пользователи чаще всего "
            "добавляли за последние сутки."
        ),
        "section": "for_you",
        "cover_image_url": "https://placehold.co/600x600/png?text=Top+24h",
        "tags": ["Хиты", "Тренды"],
        "items_total": 30,
        "sort_order": 20,
        "items": [
            {
                "title": "Беспроводные наушники",
                "description": "Универсальный подарок для музыки, звонков и спорта.",
                "link": "https://example.com/top-24-hours/headphones",
                "price": Decimal("7990.00"),
                "currency": "rub",
                "image_url": "https://placehold.co/600x800/png?text=Headphones",
                "sort_order": 10,
            },
            {
                "title": "Аромадиффузор",
                "description": "Домашний аксессуар с мягкой подсветкой и таймером.",
                "link": "https://example.com/top-24-hours/diffuser",
                "price": Decimal("3490.00"),
                "currency": "rub",
                "image_url": "https://placehold.co/600x800/png?text=Diffuser",
                "sort_order": 20,
            },
            {
                "title": "Настольная лампа",
                "description": "Сенсорное управление и регулируемая температура света.",
                "link": "https://example.com/top-24-hours/lamp",
                "price": Decimal("5290.00"),
                "currency": "rub",
                "image_url": "https://placehold.co/600x800/png?text=Lamp",
                "sort_order": 30,
            },
        ],
    },
    {
        "slug": "recently-viewed",
        "title": "Недавно смотрели",
        "subtitle": "Быстрый возврат к знакомым идеям",
        "description": (
            "Подборка вещей, к которым пользователи чаще всего "
            "возвращались за последнюю неделю."
        ),
        "section": "for_you",
        "cover_image_url": "https://placehold.co/600x600/png?text=Recent",
        "tags": ["Популярное"],
        "items_total": 15,
        "sort_order": 30,
        "items": [
            {
                "title": "Термокружка",
                "description": "Держит температуру напитка и подходит для прогулок и офиса.",
                "link": "https://example.com/recently-viewed/mug",
                "price": Decimal("2490.00"),
                "currency": "rub",
                "image_url": "https://placehold.co/600x800/png?text=Mug",
                "sort_order": 10,
            },
            {
                "title": "Плед из микрофлиса",
                "description": "Мягкий плед для уютных вечеров дома и на даче.",
                "link": "https://example.com/recently-viewed/blanket",
                "price": Decimal("3190.00"),
                "currency": "rub",
                "image_url": "https://placehold.co/600x800/png?text=Blanket",
                "sort_order": 20,
            },
            {
                "title": "Портативная колонка",
                "description": "Компактная колонка с защитой от влаги и хорошим басом.",
                "link": "https://example.com/recently-viewed/speaker",
                "price": Decimal("6990.00"),
                "currency": "rub",
                "image_url": "https://placehold.co/600x800/png?text=Speaker",
                "sort_order": 30,
            },
        ],
    },
    {
        "slug": "eternal-kids",
        "title": "Вечные дети",
        "subtitle": "Подарки для тех, кто любит игру, сюрприз и вау-эффект",
        "description": (
            "Идеи для людей, которые искренне радуются коллекционкам, "
            "играм и ярким деталям."
        ),
        "section": "by_character",
        "cover_image_url": "https://placehold.co/600x600/png?text=Eternal+Kids",
        "tags": ["Игры", "Творчество", "Коллекции"],
        "items_total": 80,
        "sort_order": 10,
        "items": [
            {
                "title": "LEGO Botanical",
                "description": "Конструктор, который приятно собирать и красиво оставить на полке.",
                "link": "https://example.com/eternal-kids/lego",
                "price": Decimal("6590.00"),
                "currency": "rub",
                "image_url": "https://placehold.co/600x800/png?text=LEGO",
                "sort_order": 10,
            },
            {
                "title": "Портативная игровая консоль",
                "description": "Ностальгия и десятки игр в одном компактном устройстве.",
                "link": "https://example.com/eternal-kids/console",
                "price": Decimal("8990.00"),
                "currency": "rub",
                "image_url": "https://placehold.co/600x800/png?text=Console",
                "sort_order": 20,
            },
            {
                "title": "Набор для рисования маркерами",
                "description": "Для тех, кто любит что-то создавать руками и раскрашивать идеи.",
                "link": "https://example.com/eternal-kids/markers",
                "price": Decimal("2790.00"),
                "currency": "rub",
                "image_url": "https://placehold.co/600x800/png?text=Markers",
                "sort_order": 30,
            },
        ],
    },
    {
        "slug": "homebodies",
        "title": "Домоседы",
        "subtitle": "Уютные подарки для спокойных вечеров",
        "description": (
            "Подборка для тех, кому особенно важны комфорт, ритуалы "
            "и приятная атмосфера дома."
        ),
        "section": "by_character",
        "cover_image_url": "https://placehold.co/600x600/png?text=Homebodies",
        "tags": ["Уют", "Дом", "Релакс"],
        "items_total": 24,
        "sort_order": 20,
        "items": [
            {
                "title": "Аромасвеча",
                "description": "Теплый древесный аромат и лаконичная банка для интерьера.",
                "link": "https://example.com/homebodies/candle",
                "price": Decimal("1590.00"),
                "currency": "rub",
                "image_url": "https://placehold.co/600x800/png?text=Candle",
                "sort_order": 10,
            },
            {
                "title": "Чайный набор",
                "description": "Подборка из четырех сортов чая для неспешных вечеров.",
                "link": "https://example.com/homebodies/tea",
                "price": Decimal("2190.00"),
                "currency": "rub",
                "image_url": "https://placehold.co/600x800/png?text=Tea",
                "sort_order": 20,
            },
            {
                "title": "Ночник с мягким светом",
                "description": "Добавляет уюта спальне и не мешает отдыхать вечером.",
                "link": "https://example.com/homebodies/night-light",
                "price": Decimal("1890.00"),
                "currency": "rub",
                "image_url": "https://placehold.co/600x800/png?text=Night+Light",
                "sort_order": 30,
            },
        ],
    },
    {
        "slug": "spooky-seasons",
        "title": "Spooky Seasons",
        "subtitle": "Сезонная коллекция для атмосферы Хэллоуина",
        "description": (
            "Небольшая редакторская подборка для праздничного настроения, "
            "декора и тематических подарков."
        ),
        "section": "editorial",
        "badge": "Временная подборка",
        "cover_image_url": "https://placehold.co/600x600/png?text=Spooky+Seasons",
        "tags": ["Хэллоуин", "Декор", "Уют"],
        "items_total": 12,
        "sort_order": 10,
        "items": [
            {
                "title": "Тыквенная гирлянда",
                "description": "Светодиодная гирлянда для праздничной атмосферы дома.",
                "link": "https://example.com/spooky-seasons/garland",
                "price": Decimal("1990.00"),
                "currency": "rub",
                "image_url": "https://placehold.co/600x800/png?text=Garland",
                "sort_order": 10,
            },
            {
                "title": "Набор тематических кружек",
                "description": "Две кружки с осенними иллюстрациями и приятной упаковкой.",
                "link": "https://example.com/spooky-seasons/mugs",
                "price": Decimal("2490.00"),
                "currency": "rub",
                "image_url": "https://placehold.co/600x800/png?text=Mugs",
                "sort_order": 20,
            },
        ],
    },
    {
        "slug": "for-second-half",
        "title": "Для второй половинки",
        "subtitle": "Подарки для любимого человека без банальных идей",
        "description": (
            "Выберите книгу, аксессуары и красивые мелочи для любимого человека - "
            "подарите возможность отвлечься от рутины и получить новые впечатления."
        ),
        "section": "editorial",
        "cover_image_url": "https://placehold.co/600x600/png?text=For+Partner",
        "tags": ["Женщине", "Мужчине"],
        "items_total": 18,
        "sort_order": 20,
        "items": [
            {
                "title": "Тинт для губ",
                "description": "Стойкий тинт в базовом оттенке для ежедневного макияжа.",
                "link": "https://example.com/for-second-half/lip-tint",
                "price": Decimal("1000.00"),
                "currency": "rub",
                "image_url": "https://placehold.co/600x800/png?text=Lip+Tint",
                "sort_order": 10,
            },
            {
                "title": "Плетеная сумка",
                "description": "Акцентный аксессуар на каждый день с выразительной фактурой.",
                "link": "https://example.com/for-second-half/bag",
                "price": Decimal("1000.00"),
                "currency": "rub",
                "image_url": "https://placehold.co/600x800/png?text=Bag",
                "sort_order": 20,
            },
            {
                "title": "Украшение с инициалом",
                "description": "Небольшой личный подарок, который приятно носить каждый день.",
                "link": "https://example.com/for-second-half/initial-necklace",
                "price": Decimal("1000.00"),
                "currency": "rub",
                "image_url": "https://placehold.co/600x800/png?text=Necklace",
                "sort_order": 30,
            },
            {
                "title": "Набор ухода за кожей",
                "description": "Готовый сет для домашнего spa-вечера с базовыми средствами.",
                "link": "https://example.com/for-second-half/skincare",
                "price": Decimal("1000.00"),
                "currency": "rub",
                "image_url": "https://placehold.co/600x800/png?text=Skincare",
                "sort_order": 40,
            },
        ],
    },
]


def seed_collections(apps, schema_editor):
    Collection = apps.get_model("api", "Collection")
    CollectionItem = apps.get_model("api", "CollectionItem")

    for collection_data in COLLECTIONS:
        items = collection_data["items"]
        defaults = {
            key: value
            for key, value in collection_data.items()
            if key not in {"slug", "items"}
        }
        collection, _created = Collection.objects.update_or_create(
            slug=collection_data["slug"],
            defaults=defaults,
        )

        kept_item_ids = []
        for item_data in items:
            item_defaults = {key: value for key, value in item_data.items() if key != "title"}
            item, _created = CollectionItem.objects.update_or_create(
                collection=collection,
                title=item_data["title"],
                defaults=item_defaults,
            )
            kept_item_ids.append(item.id)

        CollectionItem.objects.filter(collection=collection).exclude(id__in=kept_item_ids).delete()


def delete_seeded_collections(apps, schema_editor):
    Collection = apps.get_model("api", "Collection")
    Collection.objects.filter(slug__in=[collection["slug"] for collection in COLLECTIONS]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_collection_collectionitem_wishitem_collection_item_and_more"),
    ]

    operations = [
        migrations.RunPython(seed_collections, delete_seeded_collections),
    ]
