# Generated by Django 6.0.4 on 2026-05-15 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0015_merge_20260421_2338"),
    ]

    operations = [
        migrations.CreateModel(
            name="CollectionSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=64, unique=True)),
                ("title", models.CharField(max_length=255)),
                ("sort_order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.AlterField(
            model_name="collection",
            name="section",
            field=models.CharField(
                choices=[
                    ("for_you", "Подборки для вас"),
                    ("by_character", "Подборки по характеру"),
                    ("editorial", "Редакторские подборки"),
                    ("gift_ideas", "Идеи подарков"),
                ],
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="collection",
            name="sections",
            field=models.ManyToManyField(
                blank=True, related_name="collections", to="api.collectionsection"
            ),
        ),
    ]
