[tool.ruff]
line-length = 100
target-version = "py312"
exclude = [".venv"]
force-exclude = true

[tool.ruff.lint]
select = ["E", "F", "W", "I"]

[tool.bandit]
exclude_dirs = [".venv"]
targets = ["."]

[project]
name = "backend"
version = "0.1.0"
description = "GraphQL API for wishlist and calendar"
requires-python = ">=3.12"
dependencies = [
    "boto3>=1.42.45",
    "boto3-stubs~=1.42.45",
    "cryptography>=45.0.0",
    "django>=6.0.5",
    "djangorestframework>=3.16.1",
    "djangorestframework-simplejwt>=5.5.1",
    "filelock>=3.20.3",
    "gunicorn>=23.0.0",
    "pillow>=12.1.1",
    "pip>=26.1",
    "psycopg[binary]>=3.3.2",
    "pyasn1>=0.6.3",
    "pyjwt>=2.12.0",
    "python-dotenv>=1.2.1",
    "requests>=2.33.0",
    "strawberry-graphql==0.312.4",
    "strawberry-graphql-django==0.70.1",
    "urllib3>=2.7.0",
    "uvicorn>=0.38.0",
    "virtualenv>=20.36.1",
]

[dependency-groups]
dev = [
    "bandit>=1.9.2",
    "pip-audit>=2.10.0",
    "pre-commit>=4.5.1",
    "pygments>=2.20.0",
    "pytest>=8.4.2",
    "pytest-django>=4.11.1",
    "ruff>=0.14.9",
]

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "config.settings_test"
python_files = ["test_*.py", "*_test.py"]
testpaths = ["api/tests"]
