mutation LoginWithGoogle($idToken: String!) {
  loginWithGoogle(idToken: $idToken) {
    accessToken
    refreshToken
    user {
      id
      email
      username
    }
  }
}

mutation LoginWithApple($identityToken: String!, $firstName: String, $lastName: String) {
  loginWithApple(identityToken: $identityToken, firstName: $firstName, lastName: $lastName) {
    accessToken
    refreshToken
    user {
      id
      email
      username
      firstName
      lastName
    }
  }
}

mutation LoginWithYandex($oauthToken: String!) {
  loginWithYandex(oauthToken: $oauthToken) {
    accessToken
    refreshToken
    user {
      id
      email
      username
    }
  }
}

mutation RefreshToken($refreshToken: String!) {
  refreshToken(refreshToken: $refreshToken) {
    accessToken
    refreshToken
  }
}

query Me {
  me {
    id
    email
    username
    firstName
    lastName
  }
}

mutation DeleteMyAccount {
  deleteMyAccount
}
