query WishItems {
  wishItems {
    id
    title
    description
    link
    price
    currency
    imageUrl
    isFromCollection
  }
}

query WishItem($id: ID!) {
  wishItem(id: $id) {
    id
    title
    description
    link
    price
    currency
    imageUrl
    isFromCollection
  }
}

mutation CreateWishItem($title: String!, $description: String! = "", $link: String! = "", $price: Decimal = null, $currency: String! = "") {
  createWishItem(title: $title, description: $description, link: $link, price: $price, currency: $currency) {
    id
    title
    description
    link
    price
    currency
    imageUrl
    isFromCollection
  }
}

mutation UpdateWishItem($id: ID!, $title: String, $description: String, $link: String, $price: Decimal, $currency: String) {
  updateWishItem(id: $id, title: $title, description: $description, link: $link, price: $price, currency: $currency) {
    id
    title
    description
    link
    price
    currency
    imageUrl
    isFromCollection
  }
}

mutation CreateWishItemImageUpload($id: ID!, $filename: String!, $contentType: String! = "image/png") {
  createWishItemImageUpload(id: $id, filename: $filename, contentType: $contentType) {
    key
    uploadUrl
  }
}

mutation AttachWishItemImage($id: ID!, $key: String!) {
  attachWishItemImage(id: $id, key: $key) {
    id
    title
    description
    link
    price
    currency
    imageUrl
    isFromCollection
  }
}

query UserWishItems($userId: ID!) {
  userWishItems(userId: $userId) {
    user {
      id
      username
      firstName
      lastName
    }
    items {
      id
      title
      description
      link
      price
      currency
      imageUrl
      isFromCollection
    }
  }
}

mutation DeleteWishItem($id: ID!) {
  deleteWishItem(id: $id)
}
