name: CD to NAS
on:
  push:
    paths:
      - "backend/**"
      - ".github/workflows/cd.yml"

permissions:
  contents: read
  packages: read

concurrency:
  group: deploy-chooz
  cancel-in-progress: true

env:
  IMAGE_NAME: ghcr.io/hsechooz/chooz
  COMPOSE_FILE_STAGE: /volume1/docker/CHOOZ/compose.stage.yml
  COMPOSE_FILE_PROD: /volume1/docker/CHOOZ/compose.prod.yml

jobs:
  build-and-push-image:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push image
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          file: ./backend/docker/Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ github.sha }}

  deploy-stage:
    environment: staging
    runs-on: ubuntu-22.04
    permissions:
      packages: read
    needs: build-and-push-image
    timeout-minutes: 10
    steps:
      - name: SSH deploy staging
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.NAS_HOST }}
          port: ${{ secrets.NAS_PORT }}
          username: ${{ secrets.NAS_USER }}
          key: ${{ secrets.NAS_SSH_KEY }}
          script: |
            set -e
            export PATH=/usr/local/bin:$PATH

            echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin
            docker compose -f "${{ env.COMPOSE_FILE_STAGE }}" pull
            docker compose -f "${{ env.COMPOSE_FILE_STAGE }}" up -d --remove-orphans

  deploy-prod:
    environment: production
    if: github.event_name == 'push'
    runs-on: ubuntu-22.04
    permissions:
      packages: read
    needs: deploy-stage
    timeout-minutes: 10
    steps:
      - name: SSH deploy prod
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.NAS_HOST }}
          port: ${{ secrets.NAS_PORT }}
          username: ${{ secrets.NAS_USER }}
          key: ${{ secrets.NAS_SSH_KEY }}
          script: |
            set -e
            export PATH=/usr/local/bin:$PATH

            echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin
            docker compose -f "${{ env.COMPOSE_FILE_PROD }}" pull
            docker compose -f "${{ env.COMPOSE_FILE_PROD }}" up -d --remove-orphans
